### PR TITLE
Add support for ClientAssertion client auth

### PR DESCRIPTION
**Pull request by KevinDockx**
Small change that enables support for authenticating clients with assertions when calling the token endpoint (when exchanging the auth code & when refreshing tokens).

### CODE REVIEW

**Comment by leastprivilege** [comment]
Client assertion type is missing.

**Comment by KevinDockx** [comment]
The ClientAssertion class consists of Type and Value properties.  Or do you mean the enum for assertion types?  That's already in IdentityModel, I figured it would be best to keep it in one location, but if you want I can copy the enum to IdentityModel.OidcClient?

**Comment by leastprivilege** [comment]
oh sorry. my bad. Got it.

**Comment by leastprivilege** [comment]
thanks!

**Pull request merged**
