### PR TITLE
Adds a callback to perform late configuration of token validation

### PR DESCRIPTION
**Pull request by xwipeoutx**
For example, to add more issuers

### CODE REVIEW

**Comment by xwipeoutx** [comment]
So I can't repro those test failures locally, and honestly, they don't make much sense with my PR change - are there intermittent test failures in this project?

**Comment by leastprivilege** [comment]
And why do you want to do that as opposed to configure the issuers when you create the settings?

**Comment by xwipeoutx** [comment]
Perhaps I'm holding it wrong - I can't see anywhere in `OidcClientOptions` that I can do this - `ProviderInformation` has an `IssuerName`, but it doesn't have anything about accepted issuer ids.  As far as I can see, the list of issuer keys is only created in `IdentityTokenValidator.ValidateAsync` - and only supports that single `IssuerName`.

In my case I'm authenticating against Azure AAD's `common` endpoint, which returns tokens that are issued by individual tenant endpoints.

ie. Metadata URL is `https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration`, but the issuer is `"https://login.microsoftonline.com/{tenantid}/v2.0"` - replacing tenantid with a Guid.

Is there a better way to support this?

**Comment by leastprivilege** [comment]
see here

https://github.com/IdentityModel/IdentityModel.OidcClient/pull/49/files

That's why it is always better to open an issue first (or do some research) before wasting time on a PR.

**Comment by xwipeoutx** [comment]
I'd already done the code to unblock myself locally, so there wasn't much wasted time :)

That flag you mentioned doesn't cut it - I have a _list_ of valid Issuers, restricted to the tenants I want to allow access to the app.  Simply turning off issuer validation won't do that (or I have to manually check it).

Happy to move this discussion into an issue if you'd prefer.

**Comment by leastprivilege** [comment]
yes please

**Pull request closed without merging**
