### PR TITLE
Update RefreshTokenDelegatingHandler with scope

### PR DESCRIPTION
**Pull request by ashuvviet**
Refresh token with scope

### CODE REVIEW

**Comment by leastprivilege** [comment]
Hi, 

thanks!

I am not following. 

The scope parameter at refresh time is for requesting a subset of the original scopes. The handler does not do that.

Passing null should be fine. 

What exact problem are you seeing?

**Comment by ashuvviet** [comment]
Hi,

i dont think, refresh time using the original scope any more. can you check my pull request, if that make sense.

**Comment by leastprivilege** [comment]
Sorry - I do not know which problem you are trying to solve.

**Comment by ashuvviet** [comment]
ok, the issue exist from refresh token handler when it try to get new token. 
1. once the authentication is successful and application receive access , refresh, and refresh token handler.
2. use HttpClient object using this refresh token handler to call backend api's, 
3. if token is expired. 
4. this refresh token handler , check for unauthorized when token is expired and try to get new access token using previous refresh token
5. as part of step4, the scope is passed null to get new access token.

**Comment by ashuvviet** [comment]
https://github.com/IdentityModel/IdentityModel.OidcClient/pull/381

**Comment by leastprivilege** [comment]
> as part of step4, the scope is passed null to get new access token.

Yes. And how does that fail for you? What's the error? ..and are you saying this did work for before we made the change?

**Comment by ashuvviet** [comment]
yes it fails to returns new token using previous refresh token, it just returns null now. 
this below PR seems to be like breaking  refreshtoken handler. 
https://github.com/IdentityModel/IdentityModel.OidcClient/pull/374

**Comment by leastprivilege** [comment]
Which token server are you using?

**Comment by anotherexception** [comment]
@leastprivilege for info we are seeing the same issue using Auth0 (via the Auth0 nuget package) - we are on 5.1.0 which works OK, anything newer and we cannot use refresh tokens

**Comment by anotherexception** [comment]
@leastprivilege for info my issue has been fixed by this:
https://github.com/auth0/auth0-oidc-client-net/pull/254

**Pull request closed without merging**
