### PR TITLE
interface created

### PR DESCRIPTION
**Pull request by taalmod**
When using OidcClient in anther class, it is beneficial to have it implement an interface, so that the using class can be unit tested with mocks.

I have this issue in one of my apps and I would really like to be able to unittest :-)

### CODE REVIEW

**Comment by jabba2324** [comment]
Please merge this!

**Comment by leastprivilege** [comment]
Hey - will have a look. thanks!

**Comment by leastprivilege** [comment]
@brockallen opinion?

**Comment by taalmod** [comment]
Give me the weekend to correct the mistake I made.
Options need to be a part of the interface as well, otherwise they cannot be sued afterwards.

I have it corrected in the version I have offline, but need to put it up.

**Comment by leastprivilege** [comment]
Why can't you simply use a Mocking library?

**Comment by jabba2324** [comment]
@leastprivilege Most mocking libaries require an interface or the methods to be virtual/overridable. 

I think the only way to mock what we currently have is to use a library that messes with the IL which most people won't be using.

**Comment by jabba2324** [comment]
@taalmod you may also find this useful 
https://github.com/IdentityModel/IdentityModel.OidcClient2/pull/69

**Comment by taalmod** [comment]
I am indifferent to virtual methods vs interfaces, as long as I can test - thanks :-)

**Pull request closed without merging**
