### PR TITLE
Add net47 target

### PR DESCRIPTION
**Pull request by softarch74**
Keeping the oidc client library in sync with the targets for the common identity model library.

### CODE REVIEW

**Comment by leastprivilege** [comment]
Tests are failing - I am still not convinced this is the right thing to do.

**Comment by softarch74** [comment]
I'm thinking the failures are due to the fact that the base IdentityModel library that the Oidc project uses (via nuget) is still using net461. I am running local builds with both 47 variants and it seems to work fine.

Do you have any other ideas on how to address the underlying issue? Maybe remove reliance on System.Net.Http entirely?

**Comment by leastprivilege** [comment]
Replace with what?

**Comment by leastprivilege** [comment]
Should be fixed with latest

**Pull request closed without merging**
